### ISSUE TITLE
Create Representation for upper floor of Preus

### ISSUE THREAD

**Issue by AlexDikelsky** [Route-finder/Backend#37]
I'm going to make a representation for the top floor of the library. I'm not sure if there are floor plans, but I'll make sure we have some map with a JSON representation to try things with

**Comment by Isaac-List** [comment]
I put a link to the library floor plan page in a comment in an issue in the [Route-finder/Mapping](https://github.com/Route-finder/Mapping/issues/1). I think that repository or the [Route-finder/Routing](https://github.com/Route-finder/Routing) would be a better place to track this.

**Comment by Isaac-List** [comment]
Closed as off-topic in this repository.
