### ISSUE TITLE
Determine what data is needed for maps

### ISSUE THREAD

**Issue by AlexDikelsky** [Route-finder/Backend#6]
Do we need separate maps for

* The output map with real coordinates
* The map/graph we use to find shortest paths
   1. Should we use a map on the backend at all, or should it just be a graph with weights on the edges?

**Comment by AlexDikelsky** [comment]
How should
```
---------------------
| Counter           |
---------------------

----------     ----------
| A-M    |     | A-M    |
----------     ----------
```
Be represented?

**Comment by AlexDikelsky** [comment]
As we talked about, we will have a list of doubly linked cyclic lists to represent each floor.

**Comment by Isaac-List** [comment]
This has largely been solved through discussion over the last months. Closing, will reopen if it comes to be that we need more/different data to perform the mapping functionality.
