### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by AlexDikelsky** [Route-finder/Backend#9]
The database has many locations.

Locations have
* List of List of locations for the internal map representation
* Unordered list of books that are there
* Map (png, svg, ...) of the location

**Comment by Isaac-List** [comment]
Documentation for Node-Postgres module:
https://node-postgres.com/guides/project-structure

And an independently-authored getting-started guide:
https://stackabuse.com/using-postgresql-with-nodejs-and-node-postgres/
